---
abstract: "Testing Apache's Rewrite Rules"
author:
  - '=over 4'
  - 'Wakaba (id:wakabatan) <wakabatan@hatena.ne.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Apache-RewriteRules
no_index:
  directory:
    - inc
    - t
requires:
  Exporter::Lite: 0
  File::Temp: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Path::Class: 0
  Test::Differences: 0
  Test::Httpd::Apache2: 0
  Test::TCP: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hatena/perl5-test-apache-rewriterules.git
version: 1.0
